import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync, existsSync, readFileSync } from "fs";
import { join, dirname } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Load dev config for auto-copy to vault
let vaultPath = null;
try {
	const devConfig = JSON.parse(readFileSync('dev.config.json', 'utf8'));
	vaultPath = devConfig.vaultPath;
} catch (e) {
	// No dev config, skip auto-copy
}

// Copy files to vault for hot reload during development
function copyToVault() {
	if (!vaultPath || prod) return;

	try {
		// Ensure vault plugin directory exists
		if (!existsSync(vaultPath)) {
			mkdirSync(vaultPath, { recursive: true });
		}

		// Copy main.js
		copyFileSync('main.js', join(vaultPath, 'main.js'));

		// Copy manifest.json
		copyFileSync('manifest.json', join(vaultPath, 'manifest.json'));

		// Copy styles.css if exists
		if (existsSync('styles.css')) {
			copyFileSync('styles.css', join(vaultPath, 'styles.css'));
		}

		console.log('✓ Copied to vault:', vaultPath);
	} catch (err) {
		console.error('Failed to copy to vault:', err.message);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [{
		name: 'copy-to-vault',
		setup(build) {
			build.onEnd(() => {
				copyToVault();
			});
		}
	}]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
